### ISSUE TITLE
Rewrite Signature Builder and Update Packet Parser

### ISSUE THREAD

**Issue by blackphreak** [blackphreak/Feather_Server#20]
As stated in title.

## Task List
- [ ] Confirm packet documenting format
- [ ] Rewrite Signature Builder for the new format and with c#.net core
- [ ] Update Packet Parser for JSON support
